"""empty message

Revision ID: 19d631c36be2
Revises: a65e7e933c13
Create Date: 2025-06-19 10:17:03.989160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d631c36be2'
down_revision = 'a65e7e933c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('message_type',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('identity_type',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=10000),
               nullable=False)
        batch_op.alter_column('created_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('created_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('created_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_time')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('created_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=10000),
               nullable=True)
        batch_op.alter_column('identity_type',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('message_type',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('session_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
