"""empty message

Revision ID: 2caf0387d254
Revises: 32553094c72a
Create Date: 2025-06-09 16:18:46.804955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2caf0387d254'
down_revision = '32553094c72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
