"""empty message

Revision ID: 32553094c72a
Revises: 
Create Date: 2025-05-12 21:12:39.461416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32553094c72a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_patient')
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('doctor_id', 'user', ['doctor_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('doctor_id')

    op.create_table('_alembic_tmp_patient',
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('contact', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('registration_date', sa.DATE(), nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.user_id'], name='doctor_id'),
    sa.PrimaryKeyConstraint('patient_id')
    )
    # ### end Alembic commands ###
